### ISSUE TITLE
Green "TABS" button not showing correctly

### ISSUE THREAD

**Issue by Keith94** [splattael/chrome-feedly-tabs#5]
In many cases, the TABS button simply does not appear in the Feedly interface.

**Comment by splattael** [comment]
@Keith94 Happy New Year! :tada: 

Thanks for reporting :smile: Can you provide more information like Chrome version, extensions version and some screenshots of pages on which you don't see the green TABS button?

Thanks in advance :+1:

**Comment by Keith94** [comment]
Nevermind
